version: '3.8'
services:
  ai-artistic-style-service:
    image: urmsandeep/ai-artistic-style-service:latest
    container_name: ai-artistic-style
    ports:
      - "5001:5001" # Map host port 5001 to container port 5001
    restart: always # Ensure the container restarts automatically
